/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SimLabRouteImport } from './routes/sim-lab'
import { Route as SeasonLabRouteImport } from './routes/season-lab'
import { Route as LeagueRouteRouteImport } from './routes/league/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LeagueIndexRouteImport } from './routes/league/index'
import { Route as LeagueTeamRouteImport } from './routes/league/team'
import { Route as LeagueStatsRouteImport } from './routes/league/stats'
import { Route as LeagueStandingsRouteImport } from './routes/league/standings'
import { Route as LeagueScheduleRouteImport } from './routes/league/schedule'
import { Route as LeagueSavesRouteImport } from './routes/league/saves'
import { Route as LeaguePlayoffsRouteImport } from './routes/league/playoffs'
import { Route as LeaguePickTeamRouteImport } from './routes/league/pick-team'
import { Route as LeagueHistoryRouteImport } from './routes/league/history'
import { Route as LeagueDraftRouteImport } from './routes/league/draft'
import { Route as LeagueCreateRouteImport } from './routes/league/create'
import { Route as LeagueGamesGameIdRouteImport } from './routes/league/games/$gameId'

const SimLabRoute = SimLabRouteImport.update({
  id: '/sim-lab',
  path: '/sim-lab',
  getParentRoute: () => rootRouteImport,
} as any)
const SeasonLabRoute = SeasonLabRouteImport.update({
  id: '/season-lab',
  path: '/season-lab',
  getParentRoute: () => rootRouteImport,
} as any)
const LeagueRouteRoute = LeagueRouteRouteImport.update({
  id: '/league',
  path: '/league',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LeagueIndexRoute = LeagueIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LeagueRouteRoute,
} as any)
const LeagueTeamRoute = LeagueTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => LeagueRouteRoute,
} as any)
const LeagueStatsRoute = LeagueStatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => LeagueRouteRoute,
} as any)
const LeagueStandingsRoute = LeagueStandingsRouteImport.update({
  id: '/standings',
  path: '/standings',
  getParentRoute: () => LeagueRouteRoute,
} as any)
const LeagueScheduleRoute = LeagueScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => LeagueRouteRoute,
} as any)
const LeagueSavesRoute = LeagueSavesRouteImport.update({
  id: '/saves',
  path: '/saves',
  getParentRoute: () => LeagueRouteRoute,
} as any)
const LeaguePlayoffsRoute = LeaguePlayoffsRouteImport.update({
  id: '/playoffs',
  path: '/playoffs',
  getParentRoute: () => LeagueRouteRoute,
} as any)
const LeaguePickTeamRoute = LeaguePickTeamRouteImport.update({
  id: '/pick-team',
  path: '/pick-team',
  getParentRoute: () => LeagueRouteRoute,
} as any)
const LeagueHistoryRoute = LeagueHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => LeagueRouteRoute,
} as any)
const LeagueDraftRoute = LeagueDraftRouteImport.update({
  id: '/draft',
  path: '/draft',
  getParentRoute: () => LeagueRouteRoute,
} as any)
const LeagueCreateRoute = LeagueCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => LeagueRouteRoute,
} as any)
const LeagueGamesGameIdRoute = LeagueGamesGameIdRouteImport.update({
  id: '/games/$gameId',
  path: '/games/$gameId',
  getParentRoute: () => LeagueRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/league': typeof LeagueRouteRouteWithChildren
  '/season-lab': typeof SeasonLabRoute
  '/sim-lab': typeof SimLabRoute
  '/league/create': typeof LeagueCreateRoute
  '/league/draft': typeof LeagueDraftRoute
  '/league/history': typeof LeagueHistoryRoute
  '/league/pick-team': typeof LeaguePickTeamRoute
  '/league/playoffs': typeof LeaguePlayoffsRoute
  '/league/saves': typeof LeagueSavesRoute
  '/league/schedule': typeof LeagueScheduleRoute
  '/league/standings': typeof LeagueStandingsRoute
  '/league/stats': typeof LeagueStatsRoute
  '/league/team': typeof LeagueTeamRoute
  '/league/': typeof LeagueIndexRoute
  '/league/games/$gameId': typeof LeagueGamesGameIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/season-lab': typeof SeasonLabRoute
  '/sim-lab': typeof SimLabRoute
  '/league/create': typeof LeagueCreateRoute
  '/league/draft': typeof LeagueDraftRoute
  '/league/history': typeof LeagueHistoryRoute
  '/league/pick-team': typeof LeaguePickTeamRoute
  '/league/playoffs': typeof LeaguePlayoffsRoute
  '/league/saves': typeof LeagueSavesRoute
  '/league/schedule': typeof LeagueScheduleRoute
  '/league/standings': typeof LeagueStandingsRoute
  '/league/stats': typeof LeagueStatsRoute
  '/league/team': typeof LeagueTeamRoute
  '/league': typeof LeagueIndexRoute
  '/league/games/$gameId': typeof LeagueGamesGameIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/league': typeof LeagueRouteRouteWithChildren
  '/season-lab': typeof SeasonLabRoute
  '/sim-lab': typeof SimLabRoute
  '/league/create': typeof LeagueCreateRoute
  '/league/draft': typeof LeagueDraftRoute
  '/league/history': typeof LeagueHistoryRoute
  '/league/pick-team': typeof LeaguePickTeamRoute
  '/league/playoffs': typeof LeaguePlayoffsRoute
  '/league/saves': typeof LeagueSavesRoute
  '/league/schedule': typeof LeagueScheduleRoute
  '/league/standings': typeof LeagueStandingsRoute
  '/league/stats': typeof LeagueStatsRoute
  '/league/team': typeof LeagueTeamRoute
  '/league/': typeof LeagueIndexRoute
  '/league/games/$gameId': typeof LeagueGamesGameIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/league'
    | '/season-lab'
    | '/sim-lab'
    | '/league/create'
    | '/league/draft'
    | '/league/history'
    | '/league/pick-team'
    | '/league/playoffs'
    | '/league/saves'
    | '/league/schedule'
    | '/league/standings'
    | '/league/stats'
    | '/league/team'
    | '/league/'
    | '/league/games/$gameId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/season-lab'
    | '/sim-lab'
    | '/league/create'
    | '/league/draft'
    | '/league/history'
    | '/league/pick-team'
    | '/league/playoffs'
    | '/league/saves'
    | '/league/schedule'
    | '/league/standings'
    | '/league/stats'
    | '/league/team'
    | '/league'
    | '/league/games/$gameId'
  id:
    | '__root__'
    | '/'
    | '/league'
    | '/season-lab'
    | '/sim-lab'
    | '/league/create'
    | '/league/draft'
    | '/league/history'
    | '/league/pick-team'
    | '/league/playoffs'
    | '/league/saves'
    | '/league/schedule'
    | '/league/standings'
    | '/league/stats'
    | '/league/team'
    | '/league/'
    | '/league/games/$gameId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LeagueRouteRoute: typeof LeagueRouteRouteWithChildren
  SeasonLabRoute: typeof SeasonLabRoute
  SimLabRoute: typeof SimLabRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sim-lab': {
      id: '/sim-lab'
      path: '/sim-lab'
      fullPath: '/sim-lab'
      preLoaderRoute: typeof SimLabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/season-lab': {
      id: '/season-lab'
      path: '/season-lab'
      fullPath: '/season-lab'
      preLoaderRoute: typeof SeasonLabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/league': {
      id: '/league'
      path: '/league'
      fullPath: '/league'
      preLoaderRoute: typeof LeagueRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/league/': {
      id: '/league/'
      path: '/'
      fullPath: '/league/'
      preLoaderRoute: typeof LeagueIndexRouteImport
      parentRoute: typeof LeagueRouteRoute
    }
    '/league/team': {
      id: '/league/team'
      path: '/team'
      fullPath: '/league/team'
      preLoaderRoute: typeof LeagueTeamRouteImport
      parentRoute: typeof LeagueRouteRoute
    }
    '/league/stats': {
      id: '/league/stats'
      path: '/stats'
      fullPath: '/league/stats'
      preLoaderRoute: typeof LeagueStatsRouteImport
      parentRoute: typeof LeagueRouteRoute
    }
    '/league/standings': {
      id: '/league/standings'
      path: '/standings'
      fullPath: '/league/standings'
      preLoaderRoute: typeof LeagueStandingsRouteImport
      parentRoute: typeof LeagueRouteRoute
    }
    '/league/schedule': {
      id: '/league/schedule'
      path: '/schedule'
      fullPath: '/league/schedule'
      preLoaderRoute: typeof LeagueScheduleRouteImport
      parentRoute: typeof LeagueRouteRoute
    }
    '/league/saves': {
      id: '/league/saves'
      path: '/saves'
      fullPath: '/league/saves'
      preLoaderRoute: typeof LeagueSavesRouteImport
      parentRoute: typeof LeagueRouteRoute
    }
    '/league/playoffs': {
      id: '/league/playoffs'
      path: '/playoffs'
      fullPath: '/league/playoffs'
      preLoaderRoute: typeof LeaguePlayoffsRouteImport
      parentRoute: typeof LeagueRouteRoute
    }
    '/league/pick-team': {
      id: '/league/pick-team'
      path: '/pick-team'
      fullPath: '/league/pick-team'
      preLoaderRoute: typeof LeaguePickTeamRouteImport
      parentRoute: typeof LeagueRouteRoute
    }
    '/league/history': {
      id: '/league/history'
      path: '/history'
      fullPath: '/league/history'
      preLoaderRoute: typeof LeagueHistoryRouteImport
      parentRoute: typeof LeagueRouteRoute
    }
    '/league/draft': {
      id: '/league/draft'
      path: '/draft'
      fullPath: '/league/draft'
      preLoaderRoute: typeof LeagueDraftRouteImport
      parentRoute: typeof LeagueRouteRoute
    }
    '/league/create': {
      id: '/league/create'
      path: '/create'
      fullPath: '/league/create'
      preLoaderRoute: typeof LeagueCreateRouteImport
      parentRoute: typeof LeagueRouteRoute
    }
    '/league/games/$gameId': {
      id: '/league/games/$gameId'
      path: '/games/$gameId'
      fullPath: '/league/games/$gameId'
      preLoaderRoute: typeof LeagueGamesGameIdRouteImport
      parentRoute: typeof LeagueRouteRoute
    }
  }
}

interface LeagueRouteRouteChildren {
  LeagueCreateRoute: typeof LeagueCreateRoute
  LeagueDraftRoute: typeof LeagueDraftRoute
  LeagueHistoryRoute: typeof LeagueHistoryRoute
  LeaguePickTeamRoute: typeof LeaguePickTeamRoute
  LeaguePlayoffsRoute: typeof LeaguePlayoffsRoute
  LeagueSavesRoute: typeof LeagueSavesRoute
  LeagueScheduleRoute: typeof LeagueScheduleRoute
  LeagueStandingsRoute: typeof LeagueStandingsRoute
  LeagueStatsRoute: typeof LeagueStatsRoute
  LeagueTeamRoute: typeof LeagueTeamRoute
  LeagueIndexRoute: typeof LeagueIndexRoute
  LeagueGamesGameIdRoute: typeof LeagueGamesGameIdRoute
}

const LeagueRouteRouteChildren: LeagueRouteRouteChildren = {
  LeagueCreateRoute: LeagueCreateRoute,
  LeagueDraftRoute: LeagueDraftRoute,
  LeagueHistoryRoute: LeagueHistoryRoute,
  LeaguePickTeamRoute: LeaguePickTeamRoute,
  LeaguePlayoffsRoute: LeaguePlayoffsRoute,
  LeagueSavesRoute: LeagueSavesRoute,
  LeagueScheduleRoute: LeagueScheduleRoute,
  LeagueStandingsRoute: LeagueStandingsRoute,
  LeagueStatsRoute: LeagueStatsRoute,
  LeagueTeamRoute: LeagueTeamRoute,
  LeagueIndexRoute: LeagueIndexRoute,
  LeagueGamesGameIdRoute: LeagueGamesGameIdRoute,
}

const LeagueRouteRouteWithChildren = LeagueRouteRoute._addFileChildren(
  LeagueRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LeagueRouteRoute: LeagueRouteRouteWithChildren,
  SeasonLabRoute: SeasonLabRoute,
  SimLabRoute: SimLabRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
