/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SimLabRouteImport } from './routes/sim-lab'
import { Route as SeasonLabRouteImport } from './routes/season-lab'
import { Route as IndexRouteImport } from './routes/index'

const SimLabRoute = SimLabRouteImport.update({
  id: '/sim-lab',
  path: '/sim-lab',
  getParentRoute: () => rootRouteImport,
} as any)
const SeasonLabRoute = SeasonLabRouteImport.update({
  id: '/season-lab',
  path: '/season-lab',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/season-lab': typeof SeasonLabRoute
  '/sim-lab': typeof SimLabRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/season-lab': typeof SeasonLabRoute
  '/sim-lab': typeof SimLabRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/season-lab': typeof SeasonLabRoute
  '/sim-lab': typeof SimLabRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/season-lab' | '/sim-lab'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/season-lab' | '/sim-lab'
  id: '__root__' | '/' | '/season-lab' | '/sim-lab'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SeasonLabRoute: typeof SeasonLabRoute
  SimLabRoute: typeof SimLabRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sim-lab': {
      id: '/sim-lab'
      path: '/sim-lab'
      fullPath: '/sim-lab'
      preLoaderRoute: typeof SimLabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/season-lab': {
      id: '/season-lab'
      path: '/season-lab'
      fullPath: '/season-lab'
      preLoaderRoute: typeof SeasonLabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SeasonLabRoute: SeasonLabRoute,
  SimLabRoute: SimLabRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
