export const CITIES = [
  "Baltimore",
  "Portland",
  "Austin",
  "Detroit",
  "Memphis",
  "Reno",
  "Chicago",
  "Boston",
  "Denver",
  "Miami",
  "Seattle",
  "Phoenix",
  "Dallas",
  "Atlanta",
  "Cleveland",
  "Milwaukee",
  "Orlando",
  "Sacramento",
  "Minneapolis",
  "Charlotte",
  "Indianapolis",
  "Brooklyn",
  "Toronto",
  "Houston",
  "Philadelphia",
  "San Antonio",
  "Oklahoma City",
  "New Orleans",
  "Salt Lake",
  "Las Vegas",
  "Kansas City",
  "Columbus",
  "Nashville",
  "Buffalo",
  "Tampa",
]

export const NICKNAMES = [
  "Foundry",
  "Forge",
  "Comets",
  "Rivets",
  "Haze",
  "Ghosts",
  "Titans",
  "Harbor",
  "Summit",
  "Current",
  "Storm",
  "Blaze",
  "Stampede",
  "Voltage",
  "Iron",
  "Frost",
  "Pulse",
  "Crown",
  "North",
  "Flight",
  "Union",
  "Bridge",
  "Maple",
  "Rockets",
  "Liberty",
  "Spurs",
  "Thunder",
  "Bayou",
  "Jazz",
  "Aces",
  "Monarchs",
  "Crew",
  "Sound",
  "Bisons",
  "Rays",
]

export const EAST_DIVISIONS = ["atlantic", "central", "metro"] as const
export const WEST_DIVISIONS = ["pacific", "southwest", "northwest"] as const

export const CONFERENCES = [
  { id: "east", name: "East", divisions: EAST_DIVISIONS },
  { id: "west", name: "West", divisions: WEST_DIVISIONS },
] as const
