/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LeagueRouteImport } from './routes/league'
import { Route as DeveloperLabsRouteImport } from './routes/developer-labs'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LeagueIndexRouteImport } from './routes/league.index'
import { Route as LeagueStartRouteImport } from './routes/league.start'
import { Route as LeagueRosterRouteImport } from './routes/league.roster'
import { Route as LeagueFreeAgentsRouteImport } from './routes/league.free-agents'
import { Route as LeagueFinanceRouteImport } from './routes/league.finance'
import { Route as DeveloperLabsTeamAssemblyRouteImport } from './routes/developer-labs.team-assembly'
import { Route as DeveloperLabsProductionValueRouteImport } from './routes/developer-labs.production-value'
import { Route as DeveloperLabsPlayerGenerationRouteImport } from './routes/developer-labs.player-generation'
import { Route as DeveloperLabsMarketRulesRouteImport } from './routes/developer-labs.market-rules'
import { Route as DeveloperLabsGameMatchupRouteImport } from './routes/developer-labs.game-matchup'
import { Route as DeveloperLabsDraftDecisionRouteImport } from './routes/developer-labs.draft-decision'
import { Route as DeveloperLabsDevelopmentCohortsRouteImport } from './routes/developer-labs.development-cohorts'
import { Route as LeaguePlayersPlayerIdRouteImport } from './routes/league.players.$playerId'

const LeagueRoute = LeagueRouteImport.update({
  id: '/league',
  path: '/league',
  getParentRoute: () => rootRouteImport,
} as any)
const DeveloperLabsRoute = DeveloperLabsRouteImport.update({
  id: '/developer-labs',
  path: '/developer-labs',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LeagueIndexRoute = LeagueIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LeagueRoute,
} as any)
const LeagueStartRoute = LeagueStartRouteImport.update({
  id: '/start',
  path: '/start',
  getParentRoute: () => LeagueRoute,
} as any)
const LeagueRosterRoute = LeagueRosterRouteImport.update({
  id: '/roster',
  path: '/roster',
  getParentRoute: () => LeagueRoute,
} as any)
const LeagueFreeAgentsRoute = LeagueFreeAgentsRouteImport.update({
  id: '/free-agents',
  path: '/free-agents',
  getParentRoute: () => LeagueRoute,
} as any)
const LeagueFinanceRoute = LeagueFinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => LeagueRoute,
} as any)
const DeveloperLabsTeamAssemblyRoute =
  DeveloperLabsTeamAssemblyRouteImport.update({
    id: '/team-assembly',
    path: '/team-assembly',
    getParentRoute: () => DeveloperLabsRoute,
  } as any)
const DeveloperLabsProductionValueRoute =
  DeveloperLabsProductionValueRouteImport.update({
    id: '/production-value',
    path: '/production-value',
    getParentRoute: () => DeveloperLabsRoute,
  } as any)
const DeveloperLabsPlayerGenerationRoute =
  DeveloperLabsPlayerGenerationRouteImport.update({
    id: '/player-generation',
    path: '/player-generation',
    getParentRoute: () => DeveloperLabsRoute,
  } as any)
const DeveloperLabsMarketRulesRoute =
  DeveloperLabsMarketRulesRouteImport.update({
    id: '/market-rules',
    path: '/market-rules',
    getParentRoute: () => DeveloperLabsRoute,
  } as any)
const DeveloperLabsGameMatchupRoute =
  DeveloperLabsGameMatchupRouteImport.update({
    id: '/game-matchup',
    path: '/game-matchup',
    getParentRoute: () => DeveloperLabsRoute,
  } as any)
const DeveloperLabsDraftDecisionRoute =
  DeveloperLabsDraftDecisionRouteImport.update({
    id: '/draft-decision',
    path: '/draft-decision',
    getParentRoute: () => DeveloperLabsRoute,
  } as any)
const DeveloperLabsDevelopmentCohortsRoute =
  DeveloperLabsDevelopmentCohortsRouteImport.update({
    id: '/development-cohorts',
    path: '/development-cohorts',
    getParentRoute: () => DeveloperLabsRoute,
  } as any)
const LeaguePlayersPlayerIdRoute = LeaguePlayersPlayerIdRouteImport.update({
  id: '/players/$playerId',
  path: '/players/$playerId',
  getParentRoute: () => LeagueRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/developer-labs': typeof DeveloperLabsRouteWithChildren
  '/league': typeof LeagueRouteWithChildren
  '/developer-labs/development-cohorts': typeof DeveloperLabsDevelopmentCohortsRoute
  '/developer-labs/draft-decision': typeof DeveloperLabsDraftDecisionRoute
  '/developer-labs/game-matchup': typeof DeveloperLabsGameMatchupRoute
  '/developer-labs/market-rules': typeof DeveloperLabsMarketRulesRoute
  '/developer-labs/player-generation': typeof DeveloperLabsPlayerGenerationRoute
  '/developer-labs/production-value': typeof DeveloperLabsProductionValueRoute
  '/developer-labs/team-assembly': typeof DeveloperLabsTeamAssemblyRoute
  '/league/finance': typeof LeagueFinanceRoute
  '/league/free-agents': typeof LeagueFreeAgentsRoute
  '/league/roster': typeof LeagueRosterRoute
  '/league/start': typeof LeagueStartRoute
  '/league/': typeof LeagueIndexRoute
  '/league/players/$playerId': typeof LeaguePlayersPlayerIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/developer-labs': typeof DeveloperLabsRouteWithChildren
  '/developer-labs/development-cohorts': typeof DeveloperLabsDevelopmentCohortsRoute
  '/developer-labs/draft-decision': typeof DeveloperLabsDraftDecisionRoute
  '/developer-labs/game-matchup': typeof DeveloperLabsGameMatchupRoute
  '/developer-labs/market-rules': typeof DeveloperLabsMarketRulesRoute
  '/developer-labs/player-generation': typeof DeveloperLabsPlayerGenerationRoute
  '/developer-labs/production-value': typeof DeveloperLabsProductionValueRoute
  '/developer-labs/team-assembly': typeof DeveloperLabsTeamAssemblyRoute
  '/league/finance': typeof LeagueFinanceRoute
  '/league/free-agents': typeof LeagueFreeAgentsRoute
  '/league/roster': typeof LeagueRosterRoute
  '/league/start': typeof LeagueStartRoute
  '/league': typeof LeagueIndexRoute
  '/league/players/$playerId': typeof LeaguePlayersPlayerIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/developer-labs': typeof DeveloperLabsRouteWithChildren
  '/league': typeof LeagueRouteWithChildren
  '/developer-labs/development-cohorts': typeof DeveloperLabsDevelopmentCohortsRoute
  '/developer-labs/draft-decision': typeof DeveloperLabsDraftDecisionRoute
  '/developer-labs/game-matchup': typeof DeveloperLabsGameMatchupRoute
  '/developer-labs/market-rules': typeof DeveloperLabsMarketRulesRoute
  '/developer-labs/player-generation': typeof DeveloperLabsPlayerGenerationRoute
  '/developer-labs/production-value': typeof DeveloperLabsProductionValueRoute
  '/developer-labs/team-assembly': typeof DeveloperLabsTeamAssemblyRoute
  '/league/finance': typeof LeagueFinanceRoute
  '/league/free-agents': typeof LeagueFreeAgentsRoute
  '/league/roster': typeof LeagueRosterRoute
  '/league/start': typeof LeagueStartRoute
  '/league/': typeof LeagueIndexRoute
  '/league/players/$playerId': typeof LeaguePlayersPlayerIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/developer-labs'
    | '/league'
    | '/developer-labs/development-cohorts'
    | '/developer-labs/draft-decision'
    | '/developer-labs/game-matchup'
    | '/developer-labs/market-rules'
    | '/developer-labs/player-generation'
    | '/developer-labs/production-value'
    | '/developer-labs/team-assembly'
    | '/league/finance'
    | '/league/free-agents'
    | '/league/roster'
    | '/league/start'
    | '/league/'
    | '/league/players/$playerId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/developer-labs'
    | '/developer-labs/development-cohorts'
    | '/developer-labs/draft-decision'
    | '/developer-labs/game-matchup'
    | '/developer-labs/market-rules'
    | '/developer-labs/player-generation'
    | '/developer-labs/production-value'
    | '/developer-labs/team-assembly'
    | '/league/finance'
    | '/league/free-agents'
    | '/league/roster'
    | '/league/start'
    | '/league'
    | '/league/players/$playerId'
  id:
    | '__root__'
    | '/'
    | '/developer-labs'
    | '/league'
    | '/developer-labs/development-cohorts'
    | '/developer-labs/draft-decision'
    | '/developer-labs/game-matchup'
    | '/developer-labs/market-rules'
    | '/developer-labs/player-generation'
    | '/developer-labs/production-value'
    | '/developer-labs/team-assembly'
    | '/league/finance'
    | '/league/free-agents'
    | '/league/roster'
    | '/league/start'
    | '/league/'
    | '/league/players/$playerId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DeveloperLabsRoute: typeof DeveloperLabsRouteWithChildren
  LeagueRoute: typeof LeagueRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/league': {
      id: '/league'
      path: '/league'
      fullPath: '/league'
      preLoaderRoute: typeof LeagueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/developer-labs': {
      id: '/developer-labs'
      path: '/developer-labs'
      fullPath: '/developer-labs'
      preLoaderRoute: typeof DeveloperLabsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/league/': {
      id: '/league/'
      path: '/'
      fullPath: '/league/'
      preLoaderRoute: typeof LeagueIndexRouteImport
      parentRoute: typeof LeagueRoute
    }
    '/league/start': {
      id: '/league/start'
      path: '/start'
      fullPath: '/league/start'
      preLoaderRoute: typeof LeagueStartRouteImport
      parentRoute: typeof LeagueRoute
    }
    '/league/roster': {
      id: '/league/roster'
      path: '/roster'
      fullPath: '/league/roster'
      preLoaderRoute: typeof LeagueRosterRouteImport
      parentRoute: typeof LeagueRoute
    }
    '/league/free-agents': {
      id: '/league/free-agents'
      path: '/free-agents'
      fullPath: '/league/free-agents'
      preLoaderRoute: typeof LeagueFreeAgentsRouteImport
      parentRoute: typeof LeagueRoute
    }
    '/league/finance': {
      id: '/league/finance'
      path: '/finance'
      fullPath: '/league/finance'
      preLoaderRoute: typeof LeagueFinanceRouteImport
      parentRoute: typeof LeagueRoute
    }
    '/developer-labs/team-assembly': {
      id: '/developer-labs/team-assembly'
      path: '/team-assembly'
      fullPath: '/developer-labs/team-assembly'
      preLoaderRoute: typeof DeveloperLabsTeamAssemblyRouteImport
      parentRoute: typeof DeveloperLabsRoute
    }
    '/developer-labs/production-value': {
      id: '/developer-labs/production-value'
      path: '/production-value'
      fullPath: '/developer-labs/production-value'
      preLoaderRoute: typeof DeveloperLabsProductionValueRouteImport
      parentRoute: typeof DeveloperLabsRoute
    }
    '/developer-labs/player-generation': {
      id: '/developer-labs/player-generation'
      path: '/player-generation'
      fullPath: '/developer-labs/player-generation'
      preLoaderRoute: typeof DeveloperLabsPlayerGenerationRouteImport
      parentRoute: typeof DeveloperLabsRoute
    }
    '/developer-labs/market-rules': {
      id: '/developer-labs/market-rules'
      path: '/market-rules'
      fullPath: '/developer-labs/market-rules'
      preLoaderRoute: typeof DeveloperLabsMarketRulesRouteImport
      parentRoute: typeof DeveloperLabsRoute
    }
    '/developer-labs/game-matchup': {
      id: '/developer-labs/game-matchup'
      path: '/game-matchup'
      fullPath: '/developer-labs/game-matchup'
      preLoaderRoute: typeof DeveloperLabsGameMatchupRouteImport
      parentRoute: typeof DeveloperLabsRoute
    }
    '/developer-labs/draft-decision': {
      id: '/developer-labs/draft-decision'
      path: '/draft-decision'
      fullPath: '/developer-labs/draft-decision'
      preLoaderRoute: typeof DeveloperLabsDraftDecisionRouteImport
      parentRoute: typeof DeveloperLabsRoute
    }
    '/developer-labs/development-cohorts': {
      id: '/developer-labs/development-cohorts'
      path: '/development-cohorts'
      fullPath: '/developer-labs/development-cohorts'
      preLoaderRoute: typeof DeveloperLabsDevelopmentCohortsRouteImport
      parentRoute: typeof DeveloperLabsRoute
    }
    '/league/players/$playerId': {
      id: '/league/players/$playerId'
      path: '/players/$playerId'
      fullPath: '/league/players/$playerId'
      preLoaderRoute: typeof LeaguePlayersPlayerIdRouteImport
      parentRoute: typeof LeagueRoute
    }
  }
}

interface DeveloperLabsRouteChildren {
  DeveloperLabsDevelopmentCohortsRoute: typeof DeveloperLabsDevelopmentCohortsRoute
  DeveloperLabsDraftDecisionRoute: typeof DeveloperLabsDraftDecisionRoute
  DeveloperLabsGameMatchupRoute: typeof DeveloperLabsGameMatchupRoute
  DeveloperLabsMarketRulesRoute: typeof DeveloperLabsMarketRulesRoute
  DeveloperLabsPlayerGenerationRoute: typeof DeveloperLabsPlayerGenerationRoute
  DeveloperLabsProductionValueRoute: typeof DeveloperLabsProductionValueRoute
  DeveloperLabsTeamAssemblyRoute: typeof DeveloperLabsTeamAssemblyRoute
}

const DeveloperLabsRouteChildren: DeveloperLabsRouteChildren = {
  DeveloperLabsDevelopmentCohortsRoute: DeveloperLabsDevelopmentCohortsRoute,
  DeveloperLabsDraftDecisionRoute: DeveloperLabsDraftDecisionRoute,
  DeveloperLabsGameMatchupRoute: DeveloperLabsGameMatchupRoute,
  DeveloperLabsMarketRulesRoute: DeveloperLabsMarketRulesRoute,
  DeveloperLabsPlayerGenerationRoute: DeveloperLabsPlayerGenerationRoute,
  DeveloperLabsProductionValueRoute: DeveloperLabsProductionValueRoute,
  DeveloperLabsTeamAssemblyRoute: DeveloperLabsTeamAssemblyRoute,
}

const DeveloperLabsRouteWithChildren = DeveloperLabsRoute._addFileChildren(
  DeveloperLabsRouteChildren,
)

interface LeagueRouteChildren {
  LeagueFinanceRoute: typeof LeagueFinanceRoute
  LeagueFreeAgentsRoute: typeof LeagueFreeAgentsRoute
  LeagueRosterRoute: typeof LeagueRosterRoute
  LeagueStartRoute: typeof LeagueStartRoute
  LeagueIndexRoute: typeof LeagueIndexRoute
  LeaguePlayersPlayerIdRoute: typeof LeaguePlayersPlayerIdRoute
}

const LeagueRouteChildren: LeagueRouteChildren = {
  LeagueFinanceRoute: LeagueFinanceRoute,
  LeagueFreeAgentsRoute: LeagueFreeAgentsRoute,
  LeagueRosterRoute: LeagueRosterRoute,
  LeagueStartRoute: LeagueStartRoute,
  LeagueIndexRoute: LeagueIndexRoute,
  LeaguePlayersPlayerIdRoute: LeaguePlayersPlayerIdRoute,
}

const LeagueRouteWithChildren =
  LeagueRoute._addFileChildren(LeagueRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DeveloperLabsRoute: DeveloperLabsRouteWithChildren,
  LeagueRoute: LeagueRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
